#!/bin/bash
# This is the Brunch Toolkit Announcement script
announcement=("The project has not been updated in a long time, and I do not have the time or resources to maintain it." "Please do not use this toolkit, I cannot guarantee that it won't mess up your system." "PRs are welcome." )
announcement_ver="2"
# Previous Announcement Number: 1
# Don't repeat announcement numbers to ensure important updates are not missed
